---
- name: Apache - Install apache server
  apt:
    name: apache2
  tags:
    - apache

- name: Apache - Install mod_wsgi
  apt:
    name: libapache2-mod-wsgi-py3
  tags:
    - apache

- name: Apache - Cloud Snitch Web conf
  template:
    src: 090-cloudsnitch.conf.j2
    dest: /etc/apache2/sites-available/090-cloudsnitch.conf
  tags:
    - config
    - apache
  notify: Restart Apache2

- name: Apache - Disable default site
  file:
    name: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  tags:
    - apache
    - config
  notify: Restart Apache2

- name: Apache - Enable cloud_snitch_web site
  file:
    name: /etc/apache2/sites-enabled/090-cloudsnitch.conf
    state: link
    src: /etc/apache2/sites-available/090-cloudsnitch.conf
  tags:
    - config
    - apache
  notify: Restart Apache2

- name: Apache - Enable mod_wsgi
  apache2_module:
    name: wsgi
    state: present
  tags:
    - config
    - apache
  notify: Restart Apache2
