neo4j_version: '1:3.3.5'
neo4j_default_listen_address: 'localhost'
neo4j_bolt_enabled: 'true'
neo4j_bolt_port: 7687
neo4j_http_enabled: 'true'
neo4j_http_port: 7474
neo4j_https_enabled: 'true'
neo4j_https_port: 7473
neo4j_service_name: 'neo4j'
